### ISSUE TITLE
openwrt解决方案

### ISSUE THREAD

**Issue by ghost** [samuelts/client#2]
配合Crontab挂在路由器上岂不完美。
之前一直想这么干，但是由于懒癌晚期 + 拖延 == 一直将就着用iOS客户端认证和Crontab定时关WAN口

好奇你是怎么搞到 username(password)_crypto 的计算方法的

**Comment by zengxs** [comment]
要是有空就把这个加上去吧。
shell/bash还是python脚本?

**Comment by zengxs** [comment]
username的加密是和一个学弟一起抓包分析出来的，这个分析起来比较简单，加密不是很复杂。
password加密分析起来有点难度，参照了一些资料，详见master分支readme

**Comment by ghost** [comment]
路由器上还是Bash比较多吧

**Comment by zengxs** [comment]
ok

**Comment by zengxs** [comment]
openwrt解决方案: [ygqsgm/autologin-srun3k](https://github.com/ygqsgm/autologin-srun3k)
