### ISSUE TITLE
Mac版上的一些问题

### ISSUE THREAD

**Issue by Haut-Stone** [samuelts/client#5]
- 请问这个配置文件的使用方法可以写一下吗？另外请问配置文件的路径可以改吗？

![screen shot 2017-09-04 at 2 28 14 pm](https://user-images.githubusercontent.com/23383152/30014231-d0beb342-917d-11e7-86a9-3e4656ed12f1.png)

- 在mac上会有一些显示问题。

![screen shot 2017-09-04 at 2 28 42 pm](https://user-images.githubusercontent.com/23383152/30014236-d5d3476c-917d-11e7-91db-3534add53b42.png)

感谢聚聚提供优秀的开发者指南🤣

**Comment by zengxs** [comment]
pyqt 版实现的不怎么好，有很多 bug，而且只在 Windows 上测试过。

-------

配置文件位置定义在代码 [282 行](https://github.com/zeng-xs/srun3k-client/blob/7af221e5173c3f8caf76d67c0b31847868ea03ad/srun3k.py#L282)：
~~~python
path = os.path.join(os.path.expanduser("~"), 'config.json')
~~~
这一行代码表示使用 `$HOME` 目录下的 `config.json` 作为配置文件。

-------

配置文件写法可以参见 [`config.json-example`](https://github.com/zeng-xs/srun3k-client/blob/pyqt5/config.json-example) 文件。通常需要修改的应该是 `accounts` 字段：
~~~json
"accounts": {
    "default": "username1",
    "storage": {
        "username1": "password",
        "username2": "password"
    }
}
~~~

`storage` 是用于存储账号密码的字典，`key` 值为账号，`value` 为密码。`default` 值用于指示默认使用的账号。

**Comment by zengxs** [comment]
显示问题是因为没写布局，所用控件都是固定位置。

我目前没什么时间来弄这个，最多再维护一段时间 HTML 版。如果你有兴趣的话可以尝试维护一下这个分支。

**Comment by CHN-STUDENT** [comment]
建议用网页版吧。
