### ISSUE TITLE
网页版掉线蛮严重的

### ISSUE THREAD

**Issue by jissin** [samuelts/client#6]
可不可以用 js 定期发心跳包？

**Comment by anhedonia-he** [comment]
下的是最新版么？
你在什么位置

**Comment by jissin** [comment]
人在 f 区，是最新版

**Comment by anhedonia-he** [comment]
同 f 这边暂时还没问题

你是最近才开始掉的么

还有 心跳包的机制被废除了

**Comment by jissin** [comment]
今天才开始用的，发现过几分钟就会自己断开，我再测试看看

**Comment by noisky** [comment]
网页版我这里测试是不会掉的
你可以试试其他版本 目前测试不需要心跳包也不掉线 有些登录方式是不需要心跳包的
https://ffis.me/jiaowu/srun.html

**Comment by jissin** [comment]
感谢各位
